server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8081
          predicates:
            - Path=/reserves/**, 
        - id: campsite
          uri: http://localhost:8082
          predicates:
            - Path=/sites/**, 
        - id: rentalvendor
          uri: http://localhost:8083
          predicates:
            - Path=/rents/**, 
        - id: campingHistory
          uri: http://localhost:8084
          predicates:
            - Path=, /rentalnfos/**
        - id: pay
          uri: http://localhost:8085
          predicates:
            - Path=/payments/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/reserves/**, 
        - id: campsite
          uri: http://campsite:8080
          predicates:
            - Path=/sites/**, 
        - id: rentalvendor
          uri: http://rentalvendor:8080
          predicates:
            - Path=/rents/**, 
        - id: campingHistory
          uri: http://campingHistory:8080
          predicates:
            - Path=, /rentalnfos/**
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/payments/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
